apiVersion: apps/v1                # Versão da API para Deployments
kind: Deployment                   # Tipo de recurso: Deployment
metadata:
  name: apache-deploy              # Nome do Deployment
  namespace: websolutions           # Namespace onde será criado
spec:
  replicas: 2                      # Número de réplicas (2 pods de Apache)
  selector:
    matchLabels:
      app: apache-poc               # Label usada para selecionar os pods
  template:
    metadata:
      labels:
        app: apache-poc             # Label aplicada nos pods
    spec:
      containers:
        - name: apache              # Nome do container
          image: apache-poc:latest  #  Corrigido: usa a imagem que você buildou e carregou no Minikube
          ports:
            - containerPort: 80     # Porta exposta dentro do container (Apache escuta na 80)
