# Secret armazena credenciais de forma segura (em base64)

apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: websolutions
type: Opaque                        # Tipo de Secret -> dados genericos
data:                               # Valores em base64
  MYSQL_USER: d2VidXNlcg==          # Usuário do banco (webuser)
  MYSQL_PASSWORD: d2VicGFzcw==      # Senha do usuário (webpass)
  MYSQL_DATABASE: d2ViZGI=          # Nome do banco (webdb)
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M= # Senha do root (rootpass)