apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: websolutions
spec:
  type: ClusterIP             # Banco exposto apenas dentro do cluster
  selector:
    app: mariadb
  ports:
    - port: 3306              # Porta padr√£o do MySQL/MariaDB
      targetPort: 3306